-- MySQL Script generated by MySQL Workbench
-- Tue Feb 25 10:33:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema P5-blog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema P5-blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `P5-blog` DEFAULT CHARACTER SET utf8 ;
USE `P5-blog` ;

-- -----------------------------------------------------
-- Table `P5-blog`.`role_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `P5-blog`.`role_users` (
  `id_role_user` INT NOT NULL AUTO_INCREMENT,
  `entitled` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_role_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P5-blog`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `P5-blog`.`users` (
  `id_users` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `create_date` DATE NOT NULL,
  `profile_picture` VARCHAR(45) NULL,
  `role_users_id` INT NOT NULL,
  PRIMARY KEY (`id_users`),
  INDEX `fk_users_role_users_idx` (`role_users_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_role_users`
    FOREIGN KEY (`role_users_id`)
    REFERENCES `P5-blog`.`role_users` (`id_role_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P5-blog`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `P5-blog`.`posts` (
  `id_post` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `content` LONGTEXT NOT NULL,
  `short_content` TEXT(200) NOT NULL,
  `create_date` DATE NOT NULL,
  `modification_date` DATE NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id_post`),
  INDEX `fk_posts_users_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_posts_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `P5-blog`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `P5-blog`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `P5-blog`.`comments` (
  `id_comments` INT NOT NULL AUTO_INCREMENT,
  `content` LONGTEXT NOT NULL,
  `create_date` DATETIME NOT NULL,
  `validation` VARCHAR(10) NOT NULL,
  `users_id` INT NOT NULL,
  `posts_id` INT NOT NULL,
  PRIMARY KEY (`id_comments`),
  INDEX `fk_comments_users_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_comments_posts_idx` (`posts_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `P5-blog`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_posts`
    FOREIGN KEY (`posts_id`)
    REFERENCES `P5-blog`.`posts` (`id_post`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
